---
- name: Install aws packages
  apt:
    pkg: awscli
    cache_valid_time: 86400 # 1 day

- name: setup hourly cron job to sync from local sources to S3
  template:
    src: s3-backup-cron.j2
    dest: /etc/cron.hourly/s3-backup
    mode: 0700
